createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind : team
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupTeam"'
          properties:
            url:  \"https://app.clickup.com/\" + .id+ \"/home\"
            members: "[.members[].user.email]"
  - kind : project
    selector:
      query: "true" 
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupProject"'
          properties:
            url: \"https://app.clickup.com/\"+ .folder.id + /"/v/l/\"+ ,id
            startDate: .start_date
            endDate: .due_date
            totalIssues: .task_count
  - kind : issue
    selector:
      query: "true" 
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupIssue"'
          properties:
            url: .url
            status: .status.status
            assignee: .assignees
            priority: .priority
            creator: .creator.email
            created: (.date_created / 1000 | todate) 
            updated: (.date_updated / 1000 | todate)  
